### ISSUE TITLE
Gulp watch causing problems

### ISSUE THREAD

**Issue by noordawod** [formio/formio.js#1036]
Hi,
I've cloned your repo in preparation for enhancing existing components and adding more in the future, but after `npm install` and then `gulp` to startup the dev server, I get the following:

```
[08:38:38] 'watch' errored after 1.57 ms
[08:38:38] Error: watching ./src/**.js,./src/*/**.js: watch task has to be a function (optionally generated by using gulp.parallel or gulp.series)
    at Gulp.watch (/Users/noor/Projects/Formio-js/node_modules/gulp/index.js:28:11)
    at gulp.task (/Users/noor/Projects/Formio-js/gulpfile.js:129:31)
    at taskWrapper (/Users/noor/Projects/Formio-js/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (/Users/noor/Projects/Formio-js/node_modules/async-done/index.js:55:18)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
[08:38:38] 'default' errored after 21 s
```

Suspecting a problem in `gulp-watch` usage 😄 

Ideas?

**Comment by noordawod** [comment]
New with gulp-watch v4+: https://gulpjs.com/docs/en/api/watch#errors

**Comment by travist** [comment]
Thanks! We will pull in your fix for the next version.

**Comment by randallknutson** [comment]
We probably need to upgrade our gulp watch version and reconfigure it. Is this something you'd like to contribute? We can get to it in a little bit but it won't be immediate.
