### ISSUE TITLE
whatwg-fetch issue

### ISSUE THREAD

**Issue by gismomtl** [formio/formio.js#1048]
Hi,
I suspect an issue following latest update.

When launching formio (server) install, which require formio.js, I receive the following error:

 node main.js

/usr/local/app/formio/node_modules/formiojs/node_modules/whatwg-fetch/dist/fetch.umd.js:8
    searchParams: 'URLSearchParams' in self,
                                       ^

ReferenceError: self is not defined
    at /usr/local/app/formio/node_modules/formiojs/node_modules/whatwg-fetch/dist/fetch.umd.js:8:40
    at support.searchParams (/usr/local/app/formio/node_modules/formiojs/node_modules/whatwg-fetch/dist/fetch.umd.js:2:66)
    at Object.<anonymous> (/usr/local/app/formio/node_modules/formiojs/node_modules/whatwg-fetch/dist/fetch.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/app/formio/node_modules/formiojs/utils/utils.js:151:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by randallknutson** [comment]
I'm not sure what changed here. Could this be an issue in whatwg-fetch that was recently broken?

**Comment by gismomtl** [comment]
I suspect that too .. I'd to get confirmation and hopefully have a solution

**Comment by travist** [comment]
We did upgrade the whatwg-fetch library with the latest updates. I will check this library within a server environment and see what is going on.

**Comment by travist** [comment]
This is now fixed in version **3.16.1**
