### ISSUE TITLE
FormioWizard breaks on Cordova

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#234]
Hello @travist 
I'm using both FormioForm and FormioWizard on a Hybrid App. On web everything runs smooth, but when I compile the project to Cordova only FormioForm works and FormioWizard does not display (only displays the submit button with an "UNDEFINED" label on it)

Its currently giving me the following console error:

cordova.js:160 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at window.removeEventListener (file:///android_asset/www/cordova.js:160:16)
    at file:///android_asset/www/js/vendor.js:6176:16
    at arrayEach (file:///android_asset/www/js/vendor.js:73067:9)
    at forEach (file:///android_asset/www/js/vendor.js:104435:10)
    at FormioWizard.destroy (file:///android_asset/www/js/vendor.js:6175:26)
    at FormioWizard.destroy (file:///android_asset/www/js/vendor.js:49618:120)
    at FormioWizard.clear (file:///android_asset/www/js/vendor.js:6842:12)
    at file:///android_asset/www/js/vendor.js:69892:16window.removeEventListener @ cordova.js:160(anonymous function) @ vendor.js:6176arrayEach @ vendor.js:73067forEach @ vendor.js:104435destroy @ vendor.js:6175destroy @ vendor.js:49618clear @ vendor.js:6842(anonymous function) @ vendor.js:69892

Any suggestion for this?

Best regards

**Comment by cabrerabywaters** [comment]
Well, after some digging in...I found a way around it.

Seems that cordova wraps the removeEventListener function: (cordova.js 160)
'''
document.removeEventListener = function(evt, handler, capture) {
var e = evt.toLowerCase();
...
};

window.removeEventListener = function(evt, handler, capture) {
var e =  evt.toLowerCase();
...
    }
'''
At the end a simple check did the work
'''
var e = evt && evt.toLowerCase();
'''

Im not sure if its the library sending remove requests in the wrong format or a small cordova bug...but at least now its working

**Comment by travist** [comment]
What do you see in your callstack before it gets to this method?  Basically what do you see @ file:///android_asset/www/js/vendor.js:6176:16?  This will tell me if there is something in the renderer that is calling ```addEventListener``` using an undefined event object and maybe it could be fixed in the renderer.

**Comment by jhen1422** [comment]
Closed due to no user reply
