### ISSUE TITLE
Gulp build not working after pulling latest changes

### ISSUE THREAD

**Issue by asalhani** [formio/formio.js#454]
@travist @AlameerDev

The build which used to work before pulling the latest changes is not working anymore.
I'm getting below error message:

`events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Plugins.load (C:\ASALHANI\ELM_PROJECTS\ESP_NEW\ESP Component\formio.js\node_modules\eslint\lib\config\plugins.js:106:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (C:\ASALHANI\ELM_PROJECTS\ESP_NEW\ESP Component\formio.js\node_modules\eslint\lib\config\plugins.js:166:21)
    at loadFromDisk (C:\ASALHANI\ELM_PROJECTS\ESP_NEW\ESP Component\formio.js\node_modules\eslint\lib\config\config-file.js:501:35)
    at Object.load (C:\ASALHANI\ELM_PROJECTS\ESP_NEW\ESP Component\formio.js\node_modules\eslint\lib\config\config-file.js:559:20)
    at Config.getPersonalConfig (C:\ASALHANI\ELM_PROJECTS\ESP_NEW\ESP Component\formio.js\node_modules\eslint\lib\config.js:154:37)
    at Config.getLocalConfigHierarchy (C:\ASALHANI\ELM_PROJECTS\ESP_NEW\ESP Component\formio.js\node_modules\eslint\lib\config.js:248:41)
    at Config.getConfigHierarchy (C:\ASALHANI\ELM_PROJECTS\ESP_NEW\ESP Component\formio.js\node_modules\eslint\lib\config.js:179:43)`

![formio build error](https://user-images.githubusercontent.com/5410830/39967392-f431afe0-56c2-11e8-9e32-b512a56241e4.PNG)

Command I'm trying to run
`gulp build`
even running `gulp` throw the same error.

Node version: 8.11.1
NPM version:  5.8.0

Please advicse

**Comment by asalhani** [comment]
![formio build error](https://user-images.githubusercontent.com/5410830/39967040-c1fc035e-56bd-11e8-87aa-904845d29bae.PNG)

**Comment by asalhani** [comment]
Finally I got it work by commenting lines which will be exuted in `eslint ` task defined in `gulpfile.js` file
Below is the screenshot of commented lines:

![gulp error](https://user-images.githubusercontent.com/5410830/39967364-76973942-56c2-11e8-89f9-8f197f497877.png)

**Comment by travist** [comment]
I cannot seem to reproduce this issue on my machine. I even deleted the node_modules folder and ```npm install``` again and it compiles just fine.

**Comment by asalhani** [comment]
@travist 
While I'm trying to resolve the issue, I deleted node_modules and even deleted node cache folder and the issue was still there.

Anyway,  I will try another PC and get back to you soon.

**Comment by asalhani** [comment]
solved

**Comment by aa6my** [comment]
> solved

How you solve it ?
