### ISSUE TITLE
Datetime component: Can't set default date

### ISSUE THREAD

**Issue by truonghadev** [formio/formio.js#474]
Hi,
I'm trying to set default date by using 'moment();' but it didn't work.

##My json:
```
{
  "autofocus": false,
  "input": true,
  "tableView": true,
  "label": "From Date",
  "key": "fromDate",
  "placeholder": "",
  "format": "dd/MM/yyyy",
  "enableDate": true,
  "enableTime": false,
  "defaultDate": "moment();",
  "datepickerMode": "day",
  "datePicker": {
    "showWeeks": true,
    "startingDay": 0,
    "initDate": "",
    "minMode": "day",
    "maxMode": "year",
    "yearRows": 4,
    "yearColumns": 5,
    "minDate": null,
    "maxDate": null,
    "datepickerMode": "day"
  },
  "timePicker": {
    "hourStep": 1,
    "minuteStep": 1,
    "showMeridian": true,
    "readonlyInput": false,
    "mousewheel": true,
    "arrowkeys": true
  },
  "protected": false,
  "persistent": true,
  "hidden": false,
  "clearOnHide": true,
  "validate": {
    "required": true,
    "custom": ""
  },
  "type": "datetime",
  "labelPosition": "top",
  "tags": [],
  "conditional": {
    "show": "",
    "when": null,
    "eq": ""
  },
  "properties": {},
  "lockKey": true
}
```

##Moment warning:
`Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: moment();, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.eval [as createFromInputFallback] (webpack-internal:///../../../../moment/moment.js:320:98)
    at configFromString (webpack-internal:///../../../../moment/moment.js:2368:15)
    at configFromInput (webpack-internal:///../../../../moment/moment.js:2594:13)
    at prepareConfig (webpack-internal:///../../../../moment/moment.js:2577:13)
    at createFromConfig (webpack-internal:///../../../../moment/moment.js:2544:44)
    at createLocalOrUTC (webpack-internal:///../../../../moment/moment.js:2631:16)
    at createLocal (webpack-internal:///../../../../moment/moment.js:2635:16)
    at hooks (webpack-internal:///../../../../moment/moment.js:12:29)
    at getDateSetting (webpack-internal:///../../../../formiojs/lib/utils/index.js:573:44)
    at DateTimeComponent.get (webpack-internal:///../../../../formiojs/lib/components/datetime/DateTime.js:200:40)`

Please help me!

**Comment by aminmc** [comment]
I'm guessing this is related to:
https://github.com/formio/formio.js/pull/443
Is there a time when this will be released?

**Comment by jhen1422** [comment]
This issue has been resolved
