### ISSUE TITLE
[BUG] Moving tabs in tab settings causes js error

### ISSUE THREAD

**Issue by Skipperwastaken** [formio/formio.js#4857]
## Environment

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version: 4.14.8
- Frontend framework: Angular 13.3.11
- Browser: Chrome
- Browser version: 105.0.5195.102

## Steps to Reproduce
1. Create tab component, component settings open
2. Add new tab
3. Move new tab above the default tab

## Observed behavior
```
ERROR TypeError: original.children.forEach is not a function
    at Object.<anonymous> (DataGrid.js:505:1)
    at emitter (dragula.js:714:72)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (dragula.js:713:10)
    at thing.emit (dragula.js:705:48)
    at renderMirrorImage (dragula.js:475:11)
    at HTMLHtmlElement.startBecauseMouseMoved (dragula.js:190:5)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
```

**Comment by travist** [comment]
I just looked in DataGrid.js for our most recent version of the renderer and did not find any references to "children.forEach" which leads me to believe that we have already resolved this bug. Have you tried the latest renderer?
