### ISSUE TITLE
[BUG] Flatpickr renaming of el.min.js to gr.min.js breaks CalendarWidget.js

### ISSUE THREAD

**Issue by Mimisss** [formio/formio.js#4885]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: 4.14.8
- Frontend framework: Angular 14.0.0
- Browser: Google Chrome 
- Browser version: 106.0.5249.62 (Official Build) (64-bit)

## Steps to Reproduce
1. Add a DateTime Component to a form.
2. Set the form `language to `el` (Greek), for example:

   ```
   <formio    
         ...
         [renderOptions]="{language: 'el'}"
         ...>
   </formio>
   ```
3. Navigate to the form and open the browser console.

## Expected behavior

No error in console about `flatpickr`.

## Observed behavior

Console error:

```
Error: flatpickr: invalid locale el
    at re (flatpickr.min.js:2:25491)
    at flatpickr.min.js:2:38570
    at y (flatpickr.min.js:2:47971)
    at x (flatpickr.min.js:2:48258)
    at new E (flatpickr.min.js:2:48707)
    at CalendarWidget.initFlatpickr (CalendarWidget.js:568:23)
    at CalendarWidget.js:274:31
    at Function.requireLibrary (Formio.js:1850:23)
    at CalendarWidget.js:273:43
    at notifyIsolated (npo.src.js:120:15)

    Formio.js:1832          GET https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.9/l10n/el.min.js net::ERR_ABORTED 404
```

This is due to `flatpickr` renaming `el.min.js` to `gr.min.js` as shown in their CDN: https://cdnjs.com/libraries/flatpickr/4.6.9

## Flatpickr

The above has been reported to `flatpickr`, too: https://github.com/flatpickr/flatpickr/issues/2796

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
