### ISSUE TITLE
Crashing in latest CDN script

### ISSUE THREAD

**Issue by tulayha** [formio/formio.js#5272]
Facing the following error when importing the script file inside an html page using the provided cdn [link](https://cdn.form.io/formiojs/formio.full.min.js). 

```java
utils.js:462 Uncaught SyntaxError: Invalid or unexpected token (at utils.js:462:12)
    at ./lib/utils/utils.js (formio.full.js:4775:1)
    at __webpack_require__ (formio.full.js:14248:42)
    at eval (EventEmitter.js:28:37)
    at ./lib/EventEmitter.js (formio.full.js:51:1)
    at __webpack_require__ (formio.full.js:14248:42)
    at eval (Formio.js:45:44)
    at ./lib/Formio.js (formio.full.js:84:1)
    at __webpack_require__ (formio.full.js:14248:42)
    at eval (formio.form.js:109:38)
    at ./lib/formio.form.js (formio.full.js:2392:1)
``` 

On tracing the issue, it seems to be an encoding issue in the utils.js file: 
![image](https://github.com/formio/formio.js/assets/24682166/a9544423-a790-4a25-8ac2-9eaae862041b)

This causes the plugin to subsequently crash and not render on the front-end. Downgrading the main formio.full.js file to v4.14.14 locally seems to fix the issue so it has been introduced in the latest update.

**Comment by huangchinlin** [comment]
GET https://cdn.form.io/ace/1.4.12/ace.js net::ERR_ABORTED 403
GET https://cdn.form.io/flatpickr/flatpickr.min.js net::ERR_ABORTED 403
GET https://cdn.form.io/ net::ERR_ABORTED 403

I get the same situation when link to above hyperlinks today, but it's working well yesterday and before.

**Comment by brendanbond** [comment]
@huangchinlin it looks your issue specifically was a specific outage related to our CDN, but it's since been fixed and we're writing up a post mortem
