### ISSUE TITLE
Error - Headers is not defined - Nodejs

### ISSUE THREAD

**Issue by 1100617** [formio/formio.js#725]
When i do `var Formio = require('formiojs');` on node, i get this error;

```
.\node_modules\formiojs\Formio.js:1502
Formio.Headers = Headers;
                 ^

ReferenceError: Headers is not defined
    at Object.<anonymous> (.\node_modules\formiojs\Formio.js:1502:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\jose.p.ribeiro\Desktop\GlinttCamundaAPI\node_modules\formiojs\components\base\Base.js:44:38)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.\node_modules\formiojs\components\nested\NestedComponent.js:32:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```
Example:
https://runkit.com/embed/blvzmso8pbjh

**Comment by wag110894** [comment]
Hello,
This is William with the Form.io support team.
 
Thanks for reaching out! 
We have created a ticket for this issue and have tagged you on it. For reference, the ticket number is FOR-1778. We will let you know when this issue is resolved.
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by travist** [comment]
Now looking at this, the main ```Formio``` class is not compatible with Node, but should be used within the browser. You can use the FormioUtils within node using the following.

```
import FormioUtils from 'formiojs/utils';
```

If you are looking for a way to interface with the Form.io API's from Node, then you can just use the [Formio Service](https://github.com/formio/formio-service) library for that.

**Comment by dyukov** [comment]
Error happening while bundling using Webpack
`WebpackError: ReferenceError: Headers is not defined`

Caused by the following line in Formio.js
`Formio.Headers = Headers;`
